# Generated by Django 4.2.7 on 2023-12-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_review_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isFavourite',
            field=models.BooleanField(default=False),
        ),
    ]
