# Generated by Django 4.2.7 on 2023-12-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_bookmark_bookmarkitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarkitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bookmarkitem',
            name='qty',
        ),
    ]
