# Generated by Django 4.2.7 on 2023-12-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_bookmarkitem_price_remove_bookmarkitem_qty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookMarkItem',
        ),
    ]
