# Generated by Django 4.2.7 on 2023-12-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_delete_bookmarkitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='bookmarked_product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='bookmarked_product_name',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
