# Generated by Django 4.2.7 on 2023-12-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_randomnumber_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randomnumber',
            old_name='user',
            new_name='useremail',
        ),
    ]
