# Generated by Django 4.2.7 on 2023-12-13 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_user_randomnumber_useremail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randomnumber',
            old_name='useremail',
            new_name='user',
        ),
    ]
