# Generated by Django 4.2.7 on 2023-12-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_useremail_randomnumber_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['createdAt']},
        ),
    ]
