# Generated by Django 4.2.7 on 2023-12-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomnumber',
            name='user_number',
            field=models.CharField(blank=True, editable=False, max_length=6),
        ),
    ]
