# Generated by Django 4.2.7 on 2023-12-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_randomnumber_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomnumber',
            name='user_number',
            field=models.CharField(blank=True, default='6', editable=False, max_length=6),
        ),
    ]
