# Generated by Django 4.2.7 on 2023-12-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_usernumber_updating_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomnumber',
            name='user',
            field=models.EmailField(blank=True, default='larryowade3@gmail.com', max_length=99),
        ),
    ]
