# Generated by Django 4.2.7 on 2023-12-18 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0028_alter_randomnumber_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseCart',
            fields=[
                ('DatabaseCart_product_name', models.CharField(blank=True, max_length=264, null=True)),
                ('DatabaseCart_product_id', models.IntegerField(blank=True, null=True)),
                ('DatabaseCart_product_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
