# Generated by Django 4.2.7 on 2023-12-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_databasecart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasecart',
            name='DatabaseCart_product_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='databasecart',
            name='DatabaseCart_product_name',
            field=models.CharField(blank=True, editable=False, max_length=264, null=True),
        ),
    ]
