# Generated by Django 4.2.7 on 2023-12-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_databasecart_databasecart_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasecart',
            name='DatabaseCart_product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
