# Generated by Django 4.2.7 on 2023-12-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_databasecart_databasecart_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasecart',
            name='DatabaseCart_product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
