# Generated by Django 4.2.7 on 2023-12-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_order_shippingprice_alter_order_taxprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasecart',
            name='DatabaseCart_product_countinStock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
