# Generated by Django 4.2.7 on 2023-12-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
