# Generated by Django 4.2.7 on 2023-12-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_brand_product_brand_name_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
