# Generated by Django 4.2.7 on 2023-12-28 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0046_alter_specification_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleImages',
            fields=[
                ('image1', models.ImageField(blank=True, default='/meganfox.webp', null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, default='/meganfox.webp', null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, default='/meganfox.webp', null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, default='/meganfox.webp', null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, default='/meganfox.webp', null=True, upload_to='')),
                ('image6', models.ImageField(blank=True, default='/meganfox.webp', null=True, upload_to='')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
