export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const BRAND_LIST_REQUEST = 'BRAND_LIST_REQUEST'
export const BRAND_LIST_SUCCESS = 'BRAND_LIST_SUCCESS'
export const BRAND_LIST_FAIL = 'BRAND_LIST_FAIL'

export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST'
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS'
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL'


export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const CATEGORYSPECIFIC_DETAILS_REQUEST = 'CATEGORYSPECIFIC_DETAILS_REQUEST'
export const CATEGORYSPECIFIC_DETAILS_SUCCESS = 'CATEGORYSPECIFIC_DETAILS_SUCCESS'
export const CATEGORYSPECIFIC_DETAILS_FAIL = 'CATEGORYSPECIFIC_DETAILS_FAIL'

export const CATEGORY_DETAILS_REQUEST = 'CATEGORY_DETAILS_REQUEST'
export const CATEGORY_DETAILS_SUCCESS = 'CATEGORY_DETAILS_SUCCESS'
export const CATEGORY_DETAILS_FAIL = 'CATEGORY_DETAILS_FAIL'

export const BRANDSPECIFIC_DETAILS_REQUEST = 'BRANDSPECIFIC_DETAILS_REQUEST'
export const BRANDSPECIFIC_DETAILS_SUCCESS = 'BRANDSPECIFIC_DETAILS_SUCCESS'
export const BRANDSPECIFIC_DETAILS_FAIL = 'BRANDSPECIFIC_DETAILS_FAIL'

export const BRAND_DETAILS_REQUEST = 'BRAND_DETAILS_REQUEST'
export const BRAND_DETAILS_SUCCESS = 'BRAND_DETAILS_SUCCESS'
export const BRAND_DETAILS_FAIL = 'BRAND_DETAILS_FAIL'


export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'



export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'


export const PRODUCT_FAVOURITE_REQUEST = 'PRODUCT_FAVOURITE_REQUEST'
export const PRODUCT_FAVOURITE_SUCCESS = 'PRODUCT_FAVOURITE_SUCCESS'
export const PRODUCT_FAVOURITE_FAIL = 'PRODUCT_FAVOURITE_FAIL' 
export const PRODUCT_FAVOURITE_RESET = 'PRODUCT_FAVOURITE_RESET'




export const BOOKMARK_CREATE_REQUEST = 'BOOKMARK_CREATE_REQUEST'
export const BOOKMARK_CREATE_SUCCESS = 'BOOKMARK_CREATE_SUCCESS'
export const BOOKMARK_CREATE_FAIL = 'BOOKMARK_CREATE_FAIL' 
export const BOOKMARK_CREATE_RESET = 'BOOKMARK_CREATE_RESET'


export const BOOKMARK_DELETE_REQUEST = 'BOOKMARK_DELETE_REQUEST'
export const BOOKMARK_DELETE_SUCCESS = 'BOOKMARK_DELETE_SUCCESS'
export const BOOKMARK_DELETE_FAIL = 'BOOKMARK_DELETE_FAIL' 
export const BOOKMARK_DELETE_RESET = 'BOOKMARK_DELETE_RESET'

export const BOOKMARK_LIST_MY_REQUEST = 'BOOKMARK_LIST_MY_REQUEST'
export const BOOKMARK_LIST_MY_SUCCESS = 'BOOKMARK_LIST_MY_SUCCESS'
export const BOOKMARK_LIST_MY_FAIL = 'BOOKMARK_LIST_MY_FAIL' 
export const BOOKMARK_LIST_MY_RESET = 'BOOKMARK_LIST_MY_RESET' 




export const DBCART_CREATE_REQUEST = 'DBCART_CREATE_REQUEST'
export const DBCART_CREATE_SUCCESS = 'DBCART_CREATE_SUCCESS'
export const DBCART_CREATE_FAIL = 'DBCART_CREATE_FAIL' 
export const DBCART_CREATE_RESET = 'DBCART_CREATE_RESET'


export const DBCART_DELETE_REQUEST = 'DBCART_DELETE_REQUEST'
export const DBCART_DELETE_SUCCESS = 'DBCART_DELETE_SUCCESS'
export const DBCART_DELETE_FAIL = 'DBCART_DELETE_FAIL' 
export const DBCART_DELETE_RESET = 'DBCART_DELETE_RESET'

export const DBCART_LIST_MY_REQUEST = 'DBCART_LIST_MY_REQUEST'
export const DBCART_LIST_MY_SUCCESS = 'DBCART_LIST_MY_SUCCESS'
export const DBCART_LIST_MY_FAIL = 'DBCART_LIST_MY_FAIL' 
export const DBCART_LIST_MY_RESET = 'DBCART_LIST_MY_RESET' 



export const DBCART_EDIT_REQUEST = 'DBCART_EDIT_REQUEST'
export const DBCART_EDIT_SUCCESS = 'DBCART_EDIT_SUCCESS'
export const DBCART_EDIT_FAIL = 'DBCART_EDIT_FAIL' 
export const DBCART_EDIT_RESET = 'DBCART_EDIT_RESET'



export const DBCART_DETAILS_REQUEST = 'DBCART_DETAILS_REQUEST'
export const DBCART_DETAILS_SUCCESS = 'DBCART_DETAILS_SUCCESS'
export const DBCART_DETAILS_FAIL = 'DBCART_DETAILS_FAIL'



export const DBCART_CLEAR_REQUEST = 'DBCART_CLEAR_REQUEST'
export const DBCART_CLEAR_SUCCESS = 'DBCART_CLEAR_SUCCESS'
export const DBCART_CLEAR_FAIL = 'DBCART_CLEAR_FAIL' 
export const DBCART_CLEAR_RESET = 'DBCART_CLEAR_RESET'